# Generated by Django 4.1.7 on 2023-03-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoversion',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the company which should ideally be between a 100 and 155 characters', max_length=155, null=True),
        ),
    ]
