# Generated by Django 4.1.5 on 2023-08-23 08:37

from django.db import migrations, models
import django_analytics.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('modified_on', models.DateField(auto_now_add=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('clarity', models.CharField(blank=True, help_text='Microsoft clarity', max_length=20, null=True)),
                ('google_analytics', models.CharField(blank=True, help_text='Google Analytics tag', max_length=15, null=True, validators=[django_analytics.validators.google_analytics_validator])),
                ('google_ads', models.CharField(blank=True, help_text='Google ads conversion ID', max_length=20, null=True, validators=[django_analytics.validators.google_analytics_validator])),
                ('google_tag_manager', models.CharField(blank=True, help_text='Google Tag Manager container tag', max_length=15, null=True)),
                ('hotjar', models.CharField(blank=True, help_text='Hotjar configuration tag', max_length=50, null=True)),
            ],
            options={
                'ordering': ['version'],
                'abstract': False,
            },
        ),
    ]
